name: infinite_scroll_tab_view
description: A Flutter package for tab view component that can scroll infinitely.
version: 1.0.3
repository: https://github.com/cb-cloud/flutter_infinite_scroll_tab_view

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: "3.29.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
